In [8]:
import requests

from bs4 import BeautifulSoup
import pandas as pd
import time

# URL of the website to scrape
url = "https://www.scrapethissite.com/pages/simple/"

# Send an HTTP GET request to the website url
response = requests.get(url)

# Parse the HTML code with BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Extract the information from the HTML 
countries = []
for row in soup.select('div.country'):
    name = row.find('h3', class_='country-name').get_text().strip()
    capital = row.find('div', class_='country-info').find('span', class_='country-capital').get_text()
    population = row.find('div', class_='country-info').find('span', class_='country-population').get_text()
    area = row.find('div', class_='country-info').find('span', class_='country-area').get_text()
    countries.append([name, capital, population, area])

# Store the information in a pandas dataframe
df = pd.DataFrame(countries, columns=['Name', 'Capital', 'Population', 'Area'])

# To avoid overwhelming the website with requests
time.sleep(1)

df.head()

                   Name           Capital Population      Area
0               Andorra  Andorra la Vella      84000     468.0
1  United Arab Emirates         Abu Dhabi    4975593   82880.0
2           Afghanistan             Kabul   29121286  647500.0
3   Antigua and Barbuda        St. John's      86754     443.0
4              Anguilla        The Valley      13254     102.0